### ISSUE TITLE
`workflow_QC` (or its export) does not work correctly if using tables with special characters

### ISSUE THREAD

**Issue by Luxxii** [mpc-bioinformatics/ProtStatsWF#8]
Hello again!

This time with a different issue. I encode in large tables multiple list information in single cells (e.g. `[PEPTIDE]` or `[PEPTIDEA, PEPTIDEB]`).  It seems like if i encode it this way, the workflow (or its export) does not work as i would expect. 

My table is ordered as follows:

>IDENTIFIER | IntensityA, ..., IntensityZ | IdenticationA, ..., IdentificationZ | (and various other information)

If i apply the whole table, i receive the export as shown on the left.  If only applying it on the table, containing: `IDENTIFIER | IntensityA, ..., IntensityZ`, it works as "expected" (shown on the right)?

![image](https://github.com/mpc-bioinformatics/ProtStatsWF/assets/18737631/c09d5c55-091a-45d0-993f-2f1f68989c6d)

I can provide example tables if needed :)

**Comment by KarinSchork** [comment]
The workflow works but reorders the columns because everything in the id-columns is set in front. I dont know how to fix this without making this overly complicated (remembering location of the columns for example). So I will close this for now.
